typography_spectrum: 0.1227996542584151
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9718570788390934
  lightness: 0.44481284637004137
  saturation: 0.172917882213369
  rhythmicContrast: 0.7365199385676533
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4131505750119686
analytics:
  google: null
  facebook: null
  twitter: null
name: between somewhere and nowhere
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'it''s about the journey, not the destination'
description: explorations and contemplations
purpose: []
